In [317]:
import pandas as pd
import numpy as np
from jupyterthemes import jtplot
from IPython.core.display import display, HTML

display(HTML("<style>.container { width:80% !important; }</style>"))
jtplot.style()

## DataTypes & Attributes

In [318]:
# NumPy's main datatype is ndarray
# n dimensional array
# 所有的 Data 都會轉換為數字來進行機器學習, 
# 所以需要極為複雜的維度來組織 Data (數值)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [319]:
type(a1)

numpy.ndarray

In [320]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a4 = np.array([[[[2, 3],
                 [2, 3],
                 [2, 3]],
                [[2, 3],
                 [2, 3],
                 [2, 3]],
                [[2, 3],
                 [2, 3],
                 [2, 3]]],
               [[[2, 3],
                 [2, 3],
                 [2, 3]],
                [[2, 3],
                 [2, 13],
                 [2, 3]],
                [[2, 3],
                 [2, 3],
                 [2, 3]]]]

              )

In [321]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [322]:
a3.shape

(2, 3, 3)

In [323]:
a4.shape

(2, 3, 3, 2)

In [324]:
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 2, 3, 4)

In [325]:
a1.size, a2.size, a3.size, a4.size

(3, 6, 18, 36)

In [326]:
# Create a DataFrame from a NumPy array
pd.DataFrame(a2)

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [327]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [328]:
sample_array.dtype

dtype('int32')

In [329]:
ones = np.ones([1, 2])
ones

array([[1., 1.]])

In [330]:
zeros = np.zeros([1, 2])
zeros

array([[0., 0.]])

In [331]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [332]:
random_array = np.random.randint(1, 10, size=(3, 3, 3))
random_array

array([[[9, 8, 2],
        [6, 9, 8],
        [1, 8, 8]],

       [[2, 3, 6],
        [2, 1, 4],
        [8, 7, 8]],

       [[4, 2, 5],
        [1, 2, 9],
        [1, 1, 8]]])

In [333]:
random_array.size

27

In [334]:
random_array.shape

(3, 3, 3)

In [335]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.30632678, 0.55706212, 0.42833608],
       [0.15200896, 0.76099127, 0.50917861],
       [0.54768396, 0.03271778, 0.71993003],
       [0.63020705, 0.14502366, 0.74590624],
       [0.27269926, 0.04366068, 0.48224985]])

In [336]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.24078039, 0.16176249, 0.88868801],
       [0.80848299, 0.37143076, 0.66619567],
       [0.38743839, 0.12828953, 0.72463949],
       [0.71708938, 0.80747803, 0.36332494],
       [0.8982419 , 0.46666123, 0.78824869]])

In [337]:
# Pseudo-random number
# 隨機的只有種子編碼, 所以種子編碼固定後, 得到的亂數都會相同
np.random.seed(1)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

## 3. Viewing arrays and 

In [338]:
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [339]:
random_array

array([[[9, 8, 2],
        [6, 9, 8],
        [1, 8, 8]],

       [[2, 3, 6],
        [2, 1, 4],
        [8, 7, 8]],

       [[4, 2, 5],
        [1, 2, 9],
        [1, 1, 8]]])

In [340]:
random_array[:2, :2, :2]

array([[[9, 8],
        [6, 9]],

       [[2, 3],
        [2, 1]]])

In [341]:
a5 = np.random.randint(10, size=(2, 3, 4, 5))
a5.shape, a5.ndim

((2, 3, 4, 5), 4)

In [342]:
# Get the first 4 numbers of the inner most arrays
a5

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]],

        [[9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9]],

        [[2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7]]],


       [[[9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8]],

        [[4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2]],

        [[3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6],
         [6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6]]]])

In [343]:
a5[:1, :2, :3, :4]

array([[[[2, 4, 7, 7],
         [1, 7, 0, 6],
         [9, 7, 6, 9]],

        [[9, 8, 7, 3],
         [5, 1, 9, 3],
         [8, 1, 4, 0]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [344]:
a1

array([1, 2, 3])

In [345]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [346]:
a1 + ones

array([2., 3., 4.])

In [347]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [348]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [349]:
# 同一維度必須相等或其中一方為1
a3[:, :2, :1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]]])

In [350]:
a3.reshape(3, 2, 3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [351]:
a1 / ones

array([1., 2., 3.])

In [352]:
# Floor division removes the decimals (rounds down)
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [353]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [354]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [355]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [356]:
a1 + ones

array([2., 3., 4.])

In [357]:
np.add(a1, ones)

array([2., 3., 4.])

In [358]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [359]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [360]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggregation = performing the same operation on a number of things

In [361]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [362]:
sum(listy_list)

6

In [363]:
a1

array([1, 2, 3])

In [364]:
type(a1)

numpy.ndarray

In [365]:
np.sum(a1)

6

User Python's method( `sum()` ) on Python datatypes and use NumPy's methods on NumPy arrays( `np.sum()` )

In [373]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size
massive_array[:10]

array([0.84011137, 0.96132673, 0.3903379 , 0.46502647, 0.41233659,
       0.89442556, 0.54827916, 0.53901416, 0.25375655, 0.06379191])

In [374]:
%timeit sum(massive_array) # Python's sum() 
%timeit np.sum(massive_array) # NumPy's sum()

20.4 ms ± 8.28 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
41.8 µs ± 992 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [375]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [376]:
np.mean(a2)

3.6333333333333333

In [379]:
np.max(a2) ,np.min(a2), np.std(a2)

(6.5, 1.0, 1.8226964152656422)

## Reshaping & transposing

In [385]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [386]:
a2.shape

(2, 3)

In [387]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [389]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [395]:
a2.shape

(2, 3)

In [393]:
a2.T.shape

(3, 2)